import { existsSync, mkdtempSync, readFileSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { buildInitConfig, initCommand, parseServiceSelection, renderInitConfig } from "../commands/init.js";
import { SERVICE_NAMES } from "../registry.js";

describe("init helpers", () => {
  it("returns every service when no selection is provided", () => {
    expect(parseServiceSelection()).toEqual([...SERVICE_NAMES]);
  });

  it("parses a comma-separated service list and preserves order", () => {
    expect(parseServiceSelection("foundry,github,foundry")).toEqual(["foundry", "github"]);
  });

  it("throws on unknown services", () => {
    expect(() => parseServiceSelection("foundry,nope")).toThrow("Unknown service: nope");
  });

  it("builds starter config with or without shared tokens", () => {
    const withTokens = buildInitConfig(["foundry"], true);
    const withoutTokens = buildInitConfig(["foundry"], false);

    expect(withTokens).toHaveProperty("tokens");
    expect(withTokens).toHaveProperty("foundry");
    expect(withoutTokens).not.toHaveProperty("tokens");
    expect(withoutTokens).toHaveProperty("foundry");
  });

  it("renders a commented starter YAML header", () => {
    const content = renderInitConfig(["foundry"], true, "emulate.config.yaml");

    expect(content).toContain("# Generated by emulate init");
    expect(content).toContain("# Services: foundry");
    expect(content).toContain("# Start with: emulate");
    expect(content).toContain("foundry:");
  });
});

describe("initCommand", () => {
  const originalCwd = process.cwd();
  let tempDir = "";

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "emulate-init-"));
    process.chdir(tempDir);
    vi.spyOn(console, "log").mockImplementation(() => undefined);
    vi.spyOn(console, "error").mockImplementation(() => undefined);
  });

  afterEach(() => {
    vi.restoreAllMocks();
    process.chdir(originalCwd);
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("writes a selected service config to disk", async () => {
    await initCommand({ service: "foundry" });

    const content = readFileSync(join(tempDir, "emulate.config.yaml"), "utf-8");
    expect(content).toContain("foundry:");
    expect(content).toContain("oauth_clients:");
    expect(content).toContain("tokens:");
    expect(content).toContain("foundry_test_token:");
    expect(content).not.toContain("github:");
  });

  it("prints starter YAML to stdout when requested", async () => {
    const writes: string[] = [];
    const stdoutWrite = vi.spyOn(process.stdout, "write").mockImplementation(((chunk: string | Uint8Array) => {
      writes.push(typeof chunk === "string" ? chunk : Buffer.from(chunk).toString("utf-8"));
      return true;
    }) as typeof process.stdout.write);

    await initCommand({ service: "foundry", stdout: true, tokens: false });

    const output = writes.join("");

    expect(output).toContain("foundry:");
    expect(output).not.toMatch(/^tokens:/m);
    expect(existsSync(join(tempDir, "emulate.config.yaml"))).toBe(false);

    stdoutWrite.mockRestore();
  });
});
