import { cancel, confirm, intro, isCancel, multiselect, note, outro, select, text } from "@clack/prompts";
import chalk from "chalk";
import { existsSync, writeFileSync } from "fs";
import { resolve } from "path";
import { stringify as yamlStringify } from "yaml";
import { buildInitTokens, SERVICE_REGISTRY, SERVICE_NAMES, type ServiceName } from "../registry.js";

const DEFAULT_FILENAME = "emulate.config.yaml";
const AUTO_DETECTED_FILENAMES = new Set([
  "emulate.config.yaml",
  "emulate.config.yml",
  "emulate.config.json",
  "service-emulator.config.yaml",
  "service-emulator.config.yml",
  "service-emulator.config.json",
]);

type OutputMode = "file" | "stdout";

export interface InitOptions {
  service?: string;
  out?: string;
  stdout?: boolean;
  force?: boolean;
  interactive?: boolean;
  tokens?: boolean;
}

interface InitPlan {
  services: ServiceName[];
  includeTokens: boolean;
  outputMode: OutputMode;
  outPath: string;
  force: boolean;
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function parseServiceSelection(input?: string): ServiceName[] {
  const value = input?.trim();
  if (!value || value === "all") return [...SERVICE_NAMES];

  const requested = value
    .split(",")
    .map((service) => service.trim())
    .filter(Boolean);

  if (requested.length === 0) {
    throw new Error(`Select at least one service. Available: ${SERVICE_NAMES.join(", ")}, all`);
  }

  const invalid = requested.filter((service) => !(service in SERVICE_REGISTRY));
  if (invalid.length > 0) {
    throw new Error(`Unknown service: ${invalid.join(", ")}. Available: ${SERVICE_NAMES.join(", ")}, all`);
  }

  const uniqueServices: ServiceName[] = [];
  for (const service of requested as ServiceName[]) {
    if (!uniqueServices.includes(service)) uniqueServices.push(service);
  }
  return uniqueServices;
}

export function buildInitConfig(services: readonly ServiceName[], includeTokens = true): Record<string, unknown> {
  const config: Record<string, unknown> = includeTokens ? { tokens: buildInitTokens(services) } : {};

  for (const service of services) {
    const entry = SERVICE_REGISTRY[service];
    Object.assign(config, clone(entry.initConfig));
  }

  return config;
}

function shouldUseAutoDetectedPath(outPath: string): boolean {
  return AUTO_DETECTED_FILENAMES.has(outPath) || AUTO_DETECTED_FILENAMES.has(outPath.replace(/^\.\//, ""));
}

function renderExplicitSeedPath(outPath: string): string {
  return shouldUseAutoDetectedPath(outPath) ? DEFAULT_FILENAME : outPath;
}

export function renderInitConfig(
  services: readonly ServiceName[],
  includeTokens: boolean,
  outputPath?: string,
): string {
  const config = buildInitConfig(services, includeTokens);
  const header = [
    "# Generated by emulate init",
    `# Services: ${services.join(", ")}`,
    includeTokens ? "# Service-specific test tokens: included" : "# Service-specific test tokens: omitted",
  ];

  if (outputPath) {
    if (shouldUseAutoDetectedPath(outputPath)) {
      header.push("# Start with: emulate");
    } else {
      header.push(`# Start with: emulate --seed ${renderExplicitSeedPath(outputPath)}`);
    }
  } else {
    header.push(`# Save as ${DEFAULT_FILENAME} and start with: emulate`);
  }

  return `${header.join("\n")}\n\n${yamlStringify(config)}`;
}

function ensureCanWrite(outPath: string, force = false): void {
  const fullPath = resolve(outPath);
  if (!force && existsSync(fullPath)) {
    throw new Error(`Config file already exists: ${outPath}. Use --force to overwrite.`);
  }
}

function printWriteSummary(plan: InitPlan): void {
  if (plan.outputMode === "stdout") {
    console.error(chalk.green("Printed starter config to stdout."));
    console.error(chalk.dim("Tip: redirect it to a file with emulate init --stdout > emulate.config.yaml"));
    return;
  }

  const startCommand = shouldUseAutoDetectedPath(plan.outPath)
    ? "emulate"
    : `emulate --seed ${renderExplicitSeedPath(plan.outPath)}`;

  console.log(chalk.green(`Created ${plan.outPath}`));
  console.log(chalk.dim(`Bundled starter templates included: ${plan.services.join(", ")}`));
  console.log(`\nRun ${chalk.bold(startCommand)} to start the emulator.`);
}

function cancelInteractive(message = "Init cancelled."): never {
  cancel(chalk.yellow(message));
  process.exit(0);
}

function assertInteractiveSupported(): void {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error("Interactive init requires a TTY. Use flags such as --service, --out, or --stdout instead.");
  }
}

function shouldPromptInteractively(options: InitOptions): boolean {
  if (options.interactive) return true;
  if (options.stdout) return false;
  return !options.service && process.stdin.isTTY && process.stdout.isTTY;
}

async function promptForOutputPath(initialValue: string): Promise<string> {
  let currentValue = initialValue;

  for (;;) {
    const outputPath = await text({
      message: chalk.cyan("Where should the starter config be saved?"),
      defaultValue: currentValue,
      validate(value) {
        if (!value || value.trim().length === 0) return "Enter a file path.";
        return undefined;
      },
    });

    if (isCancel(outputPath)) cancelInteractive();

    const trimmedValue = outputPath.trim();
    const fullPath = resolve(trimmedValue);
    if (!existsSync(fullPath)) return trimmedValue;

    const overwrite = await confirm({
      message: chalk.yellow(`${trimmedValue} already exists. Overwrite it?`),
      initialValue: false,
      active: "overwrite",
      inactive: "choose another path",
    });

    if (isCancel(overwrite)) cancelInteractive();
    if (overwrite) return trimmedValue;
    currentValue = trimmedValue;
  }
}

async function promptInitPlan(options: InitOptions): Promise<InitPlan> {
  assertInteractiveSupported();

  const initialServices = options.service ? parseServiceSelection(options.service) : [];
  const initialIncludeTokens = options.tokens ?? true;
  const initialOutPath = options.out ?? DEFAULT_FILENAME;

  intro(chalk.bold.cyan("emulate init"));
  note(
    [
      chalk.dim("Bundled starter templates are available for every emulator service."),
      chalk.dim("Pick what you want, then save a YAML file or print it to stdout."),
    ].join("\n"),
    chalk.bold("Starter config builder"),
  );

  const selectedServices = await multiselect<ServiceName>({
    message: chalk.cyan("Select the services to include"),
    required: true,
    initialValues: initialServices,
    options: SERVICE_NAMES.map((service) => ({
      value: service,
      label: `${chalk.bold(service)} ${chalk.dim(`(${SERVICE_REGISTRY[service].label})`)}`,
      hint: SERVICE_REGISTRY[service].endpoints,
    })),
  });

  if (isCancel(selectedServices)) cancelInteractive();

  let includeTokens = initialIncludeTokens;
  if (options.tokens === undefined) {
    const answered = await confirm({
      message: chalk.cyan("Include the shared test tokens block?"),
      initialValue: true,
      active: "include tokens",
      inactive: "omit tokens",
    });

    if (isCancel(answered)) cancelInteractive();
    includeTokens = answered;
  }

  let outputMode: OutputMode = options.stdout ? "stdout" : "file";
  if (!options.stdout) {
    const answered = await select<OutputMode>({
      message: chalk.cyan("How should emulate output the starter config?"),
      initialValue: "file",
      options: [
        {
          value: "file",
          label: chalk.bold("Save to a YAML file"),
          hint: chalk.dim("Creates a reusable config you can edit and commit."),
        },
        {
          value: "stdout",
          label: chalk.bold("Print YAML to stdout"),
          hint: chalk.dim("Great for redirection, scripting, or quick previews."),
        },
      ],
    });

    if (isCancel(answered)) cancelInteractive();
    outputMode = answered;
  }

  const outPath = outputMode === "file" ? await promptForOutputPath(initialOutPath) : initialOutPath;

  note(
    [
      `${chalk.bold("Services")}  ${selectedServices.join(", ")}`,
      `${chalk.bold("Tokens")}    ${includeTokens ? "included" : "omitted"}`,
      `${chalk.bold("Output")}    ${outputMode === "file" ? outPath : "stdout"}`,
    ].join("\n"),
    chalk.bold("Plan"),
  );

  return {
    services: [...selectedServices],
    includeTokens,
    outputMode,
    outPath,
    force: true,
  };
}

function createNonInteractivePlan(options: InitOptions): InitPlan {
  if (options.stdout && options.out) {
    throw new Error("Cannot use --out together with --stdout.");
  }

  return {
    services: parseServiceSelection(options.service),
    includeTokens: options.tokens ?? true,
    outputMode: options.stdout ? "stdout" : "file",
    outPath: options.out ?? DEFAULT_FILENAME,
    force: options.force ?? false,
  };
}

export async function initCommand(options: InitOptions): Promise<void> {
  try {
    const plan = shouldPromptInteractively(options) ? await promptInitPlan(options) : createNonInteractivePlan(options);
    const content = renderInitConfig(
      plan.services,
      plan.includeTokens,
      plan.outputMode === "file" ? plan.outPath : undefined,
    );

    if (plan.outputMode === "stdout") {
      process.stdout.write(content);
      if (!content.endsWith("\n")) process.stdout.write("\n");
      printWriteSummary(plan);
      return;
    }

    ensureCanWrite(plan.outPath, plan.force);
    writeFileSync(resolve(plan.outPath), content, "utf-8");
    printWriteSummary(plan);

    if (shouldPromptInteractively(options)) {
      outro(chalk.green("Starter config ready."));
    }
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}
